sudo: required
language: rust
rust:
  - nightly-2016-06-16

cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libavahi-client-dev libavahi-common-dev libavahi-common3 libdbus-1-dev; fi

script:
  - cargo build

os:
  - linux
  - osx

notifications:
  email:
    on_success: never

branches:
  only:
    - master
